---
windows_hosts:
  vars: 
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  hosts:
    # still undefined, below is template
    # ansible_host: ipv4
    # ansible_user: admin
    # ansible_password: admin
